### ISSUE TITLE
jcf.module.ts is missing from the TypeScript

### ISSUE THREAD

**Issue by silentFred** [TrimAgency/angular-jcf-module#4]
Hey there @dominiquemiller!

Thank you for contributing this bridge for Angular 4+ Hoping to use it quite extensively!

Followed the instructions and came up with this error:

ERROR in ./node_modules/angular2-jcf-directive/jcfModule/jcf.module.tsHash: 
3364784afffdbfce1694
Time: Module build failed: Error: C:\dev\source\XXX\XXX\node_modules\angular2-jcf-directive\jcfModule\jcf.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.13203ms
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

chunk {    at AngularCompilerPlugin.getCompiledFile (C:\dev\source\XXX\XXX-ui\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
inline    at plugin.done.then (C:\dev\source\XXX\XXX-ui\node_modules\@ngtools\webpack\src\loader.js:467:39)} 
inline.bundle.js    at <anonymous> (inline) 5.79 kB 
[entry]    at process._tickCallback (internal/process/next_tick.js:169:7) [rendered]

Any help would be appreciated :)

**Comment by dominiquemiller** [comment]
Thanks for reaching out.  Unfortunately, it is difficult to figure out the error without more information.  Are you using the Angular CLI? If not, can you show me how your importing the JcfModule into your app and how your adding jquery and jcf to the project? 

We use this on many of our projects and have verified that it works with up to Angular 5.0.0.

**Comment by silentFred** [comment]
Hey there,

I'm using Angular CLI with latest release.

The import:

```
import {JcfModule} from 'angular2-jcf-directive/jcfModule/jcf.module';

@NgModule({
  imports: [
    CommonModule,
    JcfModule,
    RouterModule.forRoot(routes)
  ],
  exports: [RouterModule],
  declarations: [SomeComponent],
  providers: [
    SomeService,
    ApiClientService
  ]
})
export class SomeModule {
}
```


In angular-cli.json

```
      "styles": [
        "styles.css",
        "../node_modules/jcf/dist/css/theme-minimal/jcf.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/jcf/js/jcf.js"
      ]
```

**Comment by dominiquemiller** [comment]
Ok, I think I see the problem.  The import statement in your Module is incorrect.  It should be:
```
import { JcfModule } from '../../node_modules/angular2-jcf-directive/jcfModule/jcf.module';
```
After reviewing the documentation I noticed that we only instruct the user to import JcfModule but not explicitly declaring how to import.  I will update the documentation.

Let me know if this fixes your issue.

**Comment by silentFred** [comment]
Hi,

Seems you have to use the explicit path relative to the module you are importing it into? I'm a seasoned AngularJS dev so TS and Angular 4+ is all new to me but all other modules i have used all import by namespace/module. 

Thank you for the response. Got it working :)

**Comment by dominiquemiller** [comment]
We will be fixing that issue soon. Glad we could help you!

**Comment by silentFred** [comment]
Hey guys,

I'm trying out v0.1.2 now and still getting issues regarding the packaging:

ERROR in ./node_modules/angular2-jcf-directive/jcfModule/index.ts
Module build failed: Error: C:\dev\source\DHS_EAP\eap-member-ui\node_modules\angular2-jcf-directive\jcfModule\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\dev\source\DHS_EAP\eap-member-ui\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\dev\source\DHS_EAP\eap-member-ui\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 @ ./src/app/app.module.ngfactory.js 67:0-62
 @ ./src/main.ts
 @ multi ./src/main.ts


import { JcfModule } from 'angular2-jcf-directive/jcfModule';

@NgModule({
  imports: [
    CommonModule,
    RegistrationRoutingModule,
    BlockUIModule,
    JcfModule,
    FormsModule,
    ReactiveFormsModule
  ],
  declarations: [
    ConsentAndConditionsComponent,
    PersonalInformationComponent
  ]
})
export class RegistrationModule {
}

**Comment by dominiquemiller** [comment]
I verified your issue and it does indeed happen, not sure why at the
moment.  I will be looking into this laster today. For the time being you
can call the package directly from the node_modules folder.
import { JcfModule } from
'../../node_modules/angular2-jcf-directive/jcfModule';  That will allow
webpack to compile and you can continue to develop. I will let you know
when I have found and fixed the
issue.

**Comment by dominiquemiller** [comment]
I verified your issue and it does indeed happen, not sure why at the
moment.  I will be looking into this laster today. For the time being you
can call the package directly from the node_modules folder.
import { JcfModule } from
'../../node_modules/angular2-jcf-directive/jcfModule';
That will allow webpack to compile and you can continue to develop. I will
let you know when I have found and fixed the
issue.
